// This file was auto-generated by ML.NET Model Builder. 
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace Ml_deskriptivna
{
    public partial class MLModel1
    {
        /// <summary>
        /// model input class for MLModel1.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [ColumnName(@"Row Labels")]
            public float Row_Labels { get; set; }

            [ColumnName(@"P-104")]
            public float P_104 { get; set; }

            [ColumnName(@"P-12")]
            public float P_12 { get; set; }

            [ColumnName(@"P-140")]
            public float P_140 { get; set; }

            [ColumnName(@"P-141")]
            public float P_141 { get; set; }

            [ColumnName(@"P-142")]
            public float P_142 { get; set; }

            [ColumnName(@"P-143")]
            public float P_143 { get; set; }

            [ColumnName(@"P-145")]
            public float P_145 { get; set; }

            [ColumnName(@"P-146")]
            public float P_146 { get; set; }

            [ColumnName(@"P-147")]
            public float P_147 { get; set; }

            [ColumnName(@"P-148")]
            public float P_148 { get; set; }

            [ColumnName(@"P-149")]
            public float P_149 { get; set; }

            [ColumnName(@"P-150")]
            public float P_150 { get; set; }

            [ColumnName(@"P-151")]
            public float P_151 { get; set; }

            [ColumnName(@"P-152")]
            public float P_152 { get; set; }

            [ColumnName(@"P-153")]
            public float P_153 { get; set; }

            [ColumnName(@"P-154")]
            public float P_154 { get; set; }

            [ColumnName(@"P-155")]
            public float P_155 { get; set; }

            [ColumnName(@"P-156")]
            public float P_156 { get; set; }

            [ColumnName(@"P-157")]
            public float P_157 { get; set; }

            [ColumnName(@"P-158")]
            public float P_158 { get; set; }

            [ColumnName(@"P-159")]
            public float P_159 { get; set; }

            [ColumnName(@"P-160")]
            public float P_160 { get; set; }

            [ColumnName(@"P-161")]
            public float P_161 { get; set; }

            [ColumnName(@"P-162")]
            public float P_162 { get; set; }

            [ColumnName(@"P-175")]
            public float P_175 { get; set; }

            [ColumnName(@"P-176")]
            public float P_176 { get; set; }

            [ColumnName(@"P-177")]
            public float P_177 { get; set; }

            [ColumnName(@"P-178")]
            public float P_178 { get; set; }

            [ColumnName(@"P-218")]
            public float P_218 { get; set; }

            [ColumnName(@"P-219")]
            public float P_219 { get; set; }

            [ColumnName(@"P-220")]
            public float P_220 { get; set; }

            [ColumnName(@"P-221")]
            public float P_221 { get; set; }

            [ColumnName(@"P-222")]
            public float P_222 { get; set; }

            [ColumnName(@"P-223")]
            public float P_223 { get; set; }

            [ColumnName(@"P-224")]
            public float P_224 { get; set; }

            [ColumnName(@"P-225")]
            public float P_225 { get; set; }

            [ColumnName(@"P-226")]
            public float P_226 { get; set; }

            [ColumnName(@"P-227")]
            public float P_227 { get; set; }

            [ColumnName(@"P-228")]
            public float P_228 { get; set; }

            [ColumnName(@"P-229")]
            public float P_229 { get; set; }

            [ColumnName(@"P-230")]
            public float P_230 { get; set; }

            [ColumnName(@"P-231")]
            public float P_231 { get; set; }

            [ColumnName(@"P-232")]
            public float P_232 { get; set; }

            [ColumnName(@"P-233")]
            public float P_233 { get; set; }

            [ColumnName(@"P-234")]
            public float P_234 { get; set; }

            [ColumnName(@"P-235")]
            public float P_235 { get; set; }

            [ColumnName(@"P-236")]
            public float P_236 { get; set; }

            [ColumnName(@"P-237")]
            public float P_237 { get; set; }

            [ColumnName(@"P-238")]
            public float P_238 { get; set; }

            [ColumnName(@"P-239")]
            public float P_239 { get; set; }

            [ColumnName(@"P-24")]
            public float P_24 { get; set; }

            [ColumnName(@"P-240")]
            public float P_240 { get; set; }

            [ColumnName(@"P-241")]
            public float P_241 { get; set; }

            [ColumnName(@"P-246")]
            public float P_246 { get; set; }

            [ColumnName(@"P-247")]
            public float P_247 { get; set; }

            [ColumnName(@"P-276")]
            public float P_276 { get; set; }

            [ColumnName(@"P-277")]
            public float P_277 { get; set; }

            [ColumnName(@"P-278")]
            public float P_278 { get; set; }

            [ColumnName(@"P-279")]
            public float P_279 { get; set; }

            [ColumnName(@"P-280")]
            public float P_280 { get; set; }

            [ColumnName(@"P-33")]
            public float P_33 { get; set; }

            [ColumnName(@"P-45")]
            public float P_45 { get; set; }

            [ColumnName(@"P-50")]
            public float P_50 { get; set; }

            [ColumnName(@"P-58")]
            public float P_58 { get; set; }

            [ColumnName(@"P-7")]
            public float P_7 { get; set; }

            [ColumnName(@"P-8")]
            public float P_8 { get; set; }

            [ColumnName(@"P-85")]
            public float P_85 { get; set; }

            [ColumnName(@"P-88")]
            public float P_88 { get; set; }

            [ColumnName(@"Grand Total")]
            public float Grand_Total { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for MLModel1.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"Row Labels")]
            public float Row_Labels { get; set; }

            [ColumnName(@"P-104")]
            public uint P_104 { get; set; }

            [ColumnName(@"P-12")]
            public float P_12 { get; set; }

            [ColumnName(@"P-140")]
            public float P_140 { get; set; }

            [ColumnName(@"P-141")]
            public float P_141 { get; set; }

            [ColumnName(@"P-142")]
            public float P_142 { get; set; }

            [ColumnName(@"P-143")]
            public float P_143 { get; set; }

            [ColumnName(@"P-145")]
            public float P_145 { get; set; }

            [ColumnName(@"P-146")]
            public float P_146 { get; set; }

            [ColumnName(@"P-147")]
            public float P_147 { get; set; }

            [ColumnName(@"P-148")]
            public float P_148 { get; set; }

            [ColumnName(@"P-149")]
            public float P_149 { get; set; }

            [ColumnName(@"P-150")]
            public float P_150 { get; set; }

            [ColumnName(@"P-151")]
            public float P_151 { get; set; }

            [ColumnName(@"P-152")]
            public float P_152 { get; set; }

            [ColumnName(@"P-153")]
            public float P_153 { get; set; }

            [ColumnName(@"P-154")]
            public float P_154 { get; set; }

            [ColumnName(@"P-155")]
            public float P_155 { get; set; }

            [ColumnName(@"P-156")]
            public float P_156 { get; set; }

            [ColumnName(@"P-157")]
            public float P_157 { get; set; }

            [ColumnName(@"P-158")]
            public float P_158 { get; set; }

            [ColumnName(@"P-159")]
            public float P_159 { get; set; }

            [ColumnName(@"P-160")]
            public float P_160 { get; set; }

            [ColumnName(@"P-161")]
            public float P_161 { get; set; }

            [ColumnName(@"P-162")]
            public float P_162 { get; set; }

            [ColumnName(@"P-175")]
            public float P_175 { get; set; }

            [ColumnName(@"P-176")]
            public float P_176 { get; set; }

            [ColumnName(@"P-177")]
            public float P_177 { get; set; }

            [ColumnName(@"P-178")]
            public float P_178 { get; set; }

            [ColumnName(@"P-218")]
            public float P_218 { get; set; }

            [ColumnName(@"P-219")]
            public float P_219 { get; set; }

            [ColumnName(@"P-220")]
            public float P_220 { get; set; }

            [ColumnName(@"P-221")]
            public float P_221 { get; set; }

            [ColumnName(@"P-222")]
            public float P_222 { get; set; }

            [ColumnName(@"P-223")]
            public float P_223 { get; set; }

            [ColumnName(@"P-224")]
            public float P_224 { get; set; }

            [ColumnName(@"P-225")]
            public float P_225 { get; set; }

            [ColumnName(@"P-226")]
            public float P_226 { get; set; }

            [ColumnName(@"P-227")]
            public float P_227 { get; set; }

            [ColumnName(@"P-228")]
            public float P_228 { get; set; }

            [ColumnName(@"P-229")]
            public float P_229 { get; set; }

            [ColumnName(@"P-230")]
            public float P_230 { get; set; }

            [ColumnName(@"P-231")]
            public float P_231 { get; set; }

            [ColumnName(@"P-232")]
            public float P_232 { get; set; }

            [ColumnName(@"P-233")]
            public float P_233 { get; set; }

            [ColumnName(@"P-234")]
            public float P_234 { get; set; }

            [ColumnName(@"P-235")]
            public float P_235 { get; set; }

            [ColumnName(@"P-236")]
            public float P_236 { get; set; }

            [ColumnName(@"P-237")]
            public float P_237 { get; set; }

            [ColumnName(@"P-238")]
            public float P_238 { get; set; }

            [ColumnName(@"P-239")]
            public float P_239 { get; set; }

            [ColumnName(@"P-24")]
            public float P_24 { get; set; }

            [ColumnName(@"P-240")]
            public float P_240 { get; set; }

            [ColumnName(@"P-241")]
            public float P_241 { get; set; }

            [ColumnName(@"P-246")]
            public float P_246 { get; set; }

            [ColumnName(@"P-247")]
            public float P_247 { get; set; }

            [ColumnName(@"P-276")]
            public float P_276 { get; set; }

            [ColumnName(@"P-277")]
            public float P_277 { get; set; }

            [ColumnName(@"P-278")]
            public float P_278 { get; set; }

            [ColumnName(@"P-279")]
            public float P_279 { get; set; }

            [ColumnName(@"P-280")]
            public float P_280 { get; set; }

            [ColumnName(@"P-33")]
            public float P_33 { get; set; }

            [ColumnName(@"P-45")]
            public float P_45 { get; set; }

            [ColumnName(@"P-50")]
            public float P_50 { get; set; }

            [ColumnName(@"P-58")]
            public float P_58 { get; set; }

            [ColumnName(@"P-7")]
            public float P_7 { get; set; }

            [ColumnName(@"P-8")]
            public float P_8 { get; set; }

            [ColumnName(@"P-85")]
            public float P_85 { get; set; }

            [ColumnName(@"P-88")]
            public float P_88 { get; set; }

            [ColumnName(@"Grand Total")]
            public float Grand_Total { get; set; }

            [ColumnName(@"Features")]
            public float[] Features { get; set; }

            [ColumnName(@"PredictedLabel")]
            public float PredictedLabel { get; set; }

            [ColumnName(@"Score")]
            public float[] Score { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath("MLModel1.zip");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }

        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }
    }
}
